# Standards: 0.1
---
- name: Fact java user
  set_fact:
    java_user: "{{ java_user | default(homebrew_user) | default(ansible_user_id) }}"
  tags:
    - java

- become: "{{ (java_user != ansible_user_id) | bool }}"
  become_user: "{{ java_user }}"
  block:
    - name: Install required package
      loop: '{{ java_packages }}'
      ignore_errors: True
      homebrew_cask:
        name: "{{ item }}"
        greedy: True
        options: appdir=/Applications
        accept_external_apps: False
        state: upgraded
      tags:
        - java

...
